# redirect to jobs site
[[redirects]]
  from = "/jobs"
  to = "https://jobs.polymer.co/oops"
  status = 301
  force = false

[[redirects]]
  from = "/invite"
  to = "invite.html"
  status = 200
  force = true